[package]
name = "FGF"
version = "1.0.0"
authors = []

[addresses]
coin_owner = "0x0db874150991dce3beefd5ec2a8323a192de410846e362c0375a185a561104bf"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.LegacyCoinDeployerV2]
local = "./packages/LegacyCoinDeployerV2"

[dev-dependencies]
