[package]
name = "LegacyCoinDeployerV2"
version = "1.0.0"
authors = []

[addresses]
bapt_framework_mainnet = "0xa55a7122aa085e4bf34b755675fb900c40ee92f60c068255609ecea8ef4123f3"
bapt_framework = "0xd0ec361a55b327913690b2851cec05f1e017ec6c647689cae051644f667a1ddb" 

[dev-addresses]

[dependencies]
AptosFramework = {git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet"}
"BaptswapV2.1" = {git = "https://github.com/BAPTSWAP/V2-core.git", subdir = "", rev = "V2.1"}

[dev-dependencies]
